DROP TABLE item IF EXISTS;
DROP TABLE invoice IF EXISTS;
DROP TABLE product IF EXISTS;
DROP TABLE customer IF EXISTS;
DROP TABLE seller IF EXISTS;

CREATE TABLE product
(
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
  name             VARCHAR(255)     NOT NULL,
  price            DECIMAL          NOT NULL,
  vat              FLOAT            NOT NULL
);

CREATE TABLE customer
(
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
  first_name       VARCHAR(255)     NOT NULL,
  last_name        VARCHAR(255)     NOT NULL,
  street           VARCHAR(255)     NOT NULL,
  postal_code      VARCHAR(255)     NOT NULL,
  city             VARCHAR(255)     NOT NULL,
  country          VARCHAR(255)     NOT NULL
);

CREATE TABLE seller
(
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
  name             VARCHAR(255)     NOT NULL,
  street           VARCHAR(255)     NOT NULL,
  postal_code      VARCHAR(255)     NOT NULL,
  city             VARCHAR(255)     NOT NULL,
  country          VARCHAR(255)     NOT NULL
);

CREATE TABLE invoice
(
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
  invoice_date DATE    NOT NULL,
  seller_id    INTEGER NOT NULL,
  customer_id  INTEGER NOT NULL,

  FOREIGN KEY (seller_id) REFERENCES seller (id) ON DELETE CASCADE,
  FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE
);

CREATE TABLE item
(
  invoice_id   INTEGER      NOT NULL,
  product_id   INTEGER      NOT NULL,
  number       INT          NOT NULL,
  quantity     INT          NOT NULL,

  FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
  PRIMARY KEY(invoice_id,  product_id)
);
